# Generated by Django 5.2.18 on 2026-10-07 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Tashkilot nomi')),
                ('code', models.SlugField(unique=True, verbose_name='Tashkilot kodi')),
                ('camera_limit', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kameralar limiti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kamera raqami')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nomi')),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sig‘imi, kg')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='core.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Muzlatgich kamerasi',
                'verbose_name_plural': 'Muzlatgich kameralari',
                'ordering': ['organization_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Tashkilot admini'), ('keeper', 'Omborchi'), ('accountant', 'Buxgalter'), ('director', 'Rahbar')], default='admin', max_length=20, verbose_name='Lavozim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ruxsat faol')),
                ('all_cameras', models.BooleanField(default=False, verbose_name='Barcha kameralar (kelgusida qo‘shiladiganlar ham)')),
                ('can_receive', models.BooleanField(default=False, verbose_name='Yuk qabul qilish')),
                ('can_dispatch', models.BooleanField(default=False, verbose_name='Yuk chiqarish')),
                ('can_transfer', models.BooleanField(default=False, verbose_name='Kameralararo ko‘chirish')),
                ('can_take_payment', models.BooleanField(default=False, verbose_name='To‘lov olish')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='Moliyaviy hisobotlarni ko‘rish')),
                ('can_set_tariffs', models.BooleanField(default=False, verbose_name='Tarif belgilash')),
                ('can_dispatch_on_debt', models.BooleanField(default=False, verbose_name='Qarzga chiqarish')),
                ('cameras', models.ManyToManyField(blank=True, to='core.camera', verbose_name='Ruxsat berilgan kameralar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Administrator ruxsati',
                'verbose_name_plural': 'Administratorlar va ruxsatlar',
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_org_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_camera_number_per_org'),
        ),
    ]
