# Generated by Django 5.2.18 on 2026-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_manage_expenses',
            field=models.BooleanField(default=False, verbose_name='Xarajat kiritish'),
        ),
    ]
