# Generated by Django 5.2.18 on 2026-10-07 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_membership_can_manage_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.camera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_key', models.UUIDField(unique=True)),
                ('product', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('box_type', models.CharField(max_length=80)),
                ('received_on', models.DateField()),
                ('last_stock_date', models.DateField()),
                ('initial_boxes', models.PositiveIntegerField()),
                ('initial_gross', models.DecimalField(decimal_places=3, max_digits=14)),
                ('initial_tare', models.DecimalField(decimal_places=3, max_digits=14)),
                ('boxes', models.PositiveIntegerField()),
                ('gross', models.DecimalField(decimal_places=3, max_digits=14)),
                ('tare', models.DecimalField(decimal_places=3, max_digits=14)),
                ('tariff_name', models.CharField(max_length=120)),
                ('service', models.CharField(max_length=10)),
                ('basis', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('storage_mode', models.CharField(max_length=10)),
                ('bill_exit_day', models.BooleanField(default=False)),
                ('storage_billed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.camera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('receive', 'Kirim'), ('dispatch', 'Chiqim'), ('loss', 'Yo‘qotish'), ('transfer', 'Ko‘chirish'), ('payment', 'To‘lov'), ('storage_bill', 'Saqlama hisobi')], max_length=12)),
                ('date', models.DateField()),
                ('boxes', models.PositiveIntegerField(default=0)),
                ('gross', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tare', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('days', models.PositiveIntegerField(default=0)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payment_method', models.CharField(blank=True, max_length=12)),
                ('boxes_after', models.PositiveIntegerField(default=0)),
                ('gross_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tare_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.camera')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='warehouse.lot')),
                ('target_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.camera')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('service', models.CharField(choices=[('cooling', 'Sovutish'), ('storage', 'Saqlama')], max_length=10)),
                ('basis', models.CharField(choices=[('net', 'Sof kg'), ('gross', 'Brutto kg')], default='net', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('storage_mode', models.CharField(choices=[('prorata', 'Kuniga ulush'), ('full', 'Boshlangan oy to‘liq')], default='prorata', max_length=10)),
                ('bill_exit_day', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
    ]
