# Generated by Django 5.2.18 on 2026-10-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('since', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='warehouse.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('receive', 'Kirim'), ('dispatch', 'Chiqim'), ('loss', 'Yo‘qotish'), ('transfer', 'Ko‘chirish'), ('payment', 'To‘lov'), ('storage_bill', 'Saqlama hisobi'), ('reversal', 'Bekor qilish')], max_length=12),
        ),
    ]
